name = "pacrob"
description = "movement and languages and software, oh my!"
keywords = "crossfit, yoga, lagree, dutch, spanish, russian, python, ethereum"
image = "zenguin.jpg"
theme = "dark"
primary_color = "#d81b60"
text_align = "center"
gtag_id = ""
base_url = "https://pacrob.github.io/pacrob"

[[sections]]
title = "Things I Like"
description = "Here are some of my favorite things"
direction = "column"
item_style = "outline"
[[sections.items]]
title = "Saturday Morning Breakfast Cereal"
description = "A smart/funny comic about smart/funny stuff."
url = "https://www.smbc-comics.com/"
[[sections.items]]
title = "CrossFit"
description = "A good way to get working out for someone who doesn't know where to start working out"
url = "https://crossfit.com"
[[sections.items]]
title = "Italki"
description = "Talk to someone in another language!"
url = "https://italki.com"
[[sections.items]]
title = "The Slavic Lit Pod"
description = "Feel like you understand Tolstoy and Dostoevsky without having to do any of the work."
url = "https://slaviclitpod.com"

[[sections]]
title = "Links"
description = "This is where I am on the internet"
direction = "row"
item_style = "filled"
[[sections.items]]
title = "Linkedin"
url = "https://www.linkedin.com/in/pacrob/"
[[sections.items]]
title = "Github"
url = "https://github.com/pacrob"
